import random

GREETINGS = [
    "Ahoj",
    "Ahoj",
    "At my age, there is really only one big surprise left, and I'd just as soon leave it a mystery",
    "Barev Dzez",
    "Bok",
    "Bonjour",
    "Bonjour",
    "Ciao",
    "Cześć",
    "Dobar dan",
    "Dobriy den",
    "Geia sas",
    "Góðan dag",
    "Goeie dei",
    "Guten tag",
    "Hallå",
    "Hallo",
    "Hallo",
    "Hei",
    "Hej",
    "Helo",
    "Hola",
    "I know you're not supposed to cry over spilled tea, but it's just so sad!",
    "Jó napot",
    "Kaixo",
    "Komentari",
    "Merhaba",
    "Moïen",
    "Olá",
    "Përshëndetje",
    "Salut",
    "Salve",
    "Sharing tea with a fascinating stranger is one of life's true delights",
    "Sholem aleikhem",
    "Sick of tea? That's like being sick of breathing!",
    "Sveiki",
    "Tere",
    "This tea is nothing more than hot leaf juice!",
    "Who would have thought that, after all these years, I would return to the scene of my greatest military disgrace . . . As a tourist!",
    "Zdraveĭte",
    "Zdravo",
    "Zdravo",
    "Zdravstvujtie",
    "Zdravstvuyte",
    "Živjo"
]

def greet():
    return random.choice(GREETINGS)
